// Leashed Course Catalog & Syllabi — All modules across 15 pathways
// EVERY field in this file is sourced from the Leashed Course Catalog & Syllabi document.
// 147 modules total. Module codes, titles, hours, and descriptions are verbatim from the catalog.

export type TrackCode =
  | "VET"
  | "VTE"
  | "VST"
  | "VPM"
  | "VTN"
  | "PVM"
  | "VPT"
  | "EQN"
  | "GRO"
  | "FEL"
  | "ZKA"
  | "PRT"
  | "ABT"
  | "ACA"
  | "GSP"
  ;

export interface CatalogModule {
  code: string;
  title: string;
  trackCode: TrackCode;
  trackTitle: string;
  term: number;
  level: '100' | '200' | '300' | '400';
  hours: number;
  category: 'Technical' | 'Business' | 'Personal' | 'Applied Capstone';
  safetyGate?: boolean;
  practicum?: boolean;
  description: string;
  slug: string;
}

export const ALL_CATALOG_MODULES: CatalogModule[] = [
  // ==========================================
  // VET — Veterinary Assistant (12 modules)
  // ==========================================
  {
    code: "VET-101",
    title: "Veterinary Foundations & Medical Terminology",
    trackCode: "VET",
    trackTitle: "Veterinary Assistant",
    term: 1,
    level: '100',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Introduces foundational veterinary medical terminology, anatomy basics, and body systems. Students learn the language of veterinary medicine, directional terms, anatomical planes, and the structure and function of major body systems. This course establishes the vocabulary and conceptual framework required for all…",
    slug: "veterinary-assistant",
  },
  {
    code: "VET-102",
    title: "Animal Behavior, Handling & Restraint Techniques",
    trackCode: "VET",
    trackTitle: "Veterinary Assistant",
    term: 1,
    level: '100',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers principles of animal behavior, safe handling, and restraint techniques for companion and domestic animals. Students learn species-specific behavior patterns, fear and stress signals, and low-stress handling methods. Emphasis is placed on safety for both the animal and the veterinary healthcare team.",
    slug: "veterinary-assistant",
  },
  {
    code: "VET-103",
    title: "Office Procedures & Hospital Management",
    trackCode: "VET",
    trackTitle: "Veterinary Assistant",
    term: 1,
    level: '100',
    hours: 30,
    category: 'Technical',
    safetyGate: false,
    description: "Introduces veterinary hospital operations including scheduling, billing, medical record keeping, and office etiquette. Students learn the workflow of a veterinary practice, client intake procedures, and the role of the veterinary assistant in maintaining efficient hospital operations.",
    slug: "veterinary-assistant",
  },
  {
    code: "VET-104",
    title: "Examination Room Procedures & Client Communication",
    trackCode: "VET",
    trackTitle: "Veterinary Assistant",
    term: 2,
    level: '200',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers examination room protocols, patient intake, vital signs assessment, and effective client communication. Students learn to assist veterinarians during examinations, communicate treatment plans to clients, and maintain professional conduct and ethics in client interactions.",
    slug: "veterinary-assistant",
  },
  {
    code: "VET-105",
    title: "Pharmacy & Pharmacology Fundamentals",
    trackCode: "VET",
    trackTitle: "Veterinary Assistant",
    term: 2,
    level: '200',
    hours: 30,
    category: 'Technical',
    safetyGate: false,
    description: "Introduces basic pharmacology principles, drug classifications, dosage calculations, and pharmacy management in the veterinary setting. Students learn about common veterinary medications, controlled substance handling, and safety protocols for medication administration.",
    slug: "veterinary-assistant",
  },
  {
    code: "VET-106",
    title: "Small & Large Animal Nursing",
    trackCode: "VET",
    trackTitle: "Veterinary Assistant",
    term: 2,
    level: '200',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers nursing care for small and large animals including feeding, housing, sanitation, and patient monitoring. Students learn species-specific care requirements, domestic animal husbandry, and fundamental nursing procedures for both companion and production animals.",
    slug: "veterinary-assistant",
  },
  {
    code: "VET-107",
    title: "Surgical Preparation & Assisting",
    trackCode: "VET",
    trackTitle: "Veterinary Assistant",
    term: 2,
    level: '200',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Teaches surgical preparation protocols including patient prep, sterilization, instrument identification, and intraoperative assisting. Students learn aseptic technique, surgical room procedures, and the role of the veterinary assistant during surgical procedures.",
    slug: "veterinary-assistant",
  },
  {
    code: "VET-108",
    title: "Radiology, Imaging & Endoscopy",
    trackCode: "VET",
    trackTitle: "Veterinary Assistant",
    term: 2,
    level: '200',
    hours: 30,
    category: 'Technical',
    safetyGate: false,
    description: "Introduces diagnostic imaging including radiography, ultrasound, and endoscopy. Students learn radiation safety, patient positioning for imaging, equipment operation basics, and the veterinary assistant's role in imaging procedures.",
    slug: "veterinary-assistant",
  },
  {
    code: "VET-109",
    title: "Emergency Care, Wound Management & Common Diseases",
    trackCode: "VET",
    trackTitle: "Veterinary Assistant",
    term: 2,
    level: '200',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers emergency response protocols, wound care techniques, and recognition of common animal diseases. Students learn triage procedures, first aid, wound assessment and management, and disease prevention strategies.",
    slug: "veterinary-assistant",
  },
  {
    code: "VET-110",
    title: "Veterinary Laboratory Procedures",
    trackCode: "VET",
    trackTitle: "Veterinary Assistant",
    term: 2,
    level: '200',
    hours: 30,
    category: 'Technical',
    safetyGate: false,
    description: "Introduces basic laboratory procedures including sample collection, handling, and common diagnostic tests. Students learn to assist with laboratory diagnostics, maintain lab equipment, and understand reference ranges.",
    slug: "veterinary-assistant",
  },
  {
    code: "VET-111",
    title: "Introduction to Veterinary Telehealth & Teletriage",
    trackCode: "VET",
    trackTitle: "Veterinary Assistant",
    term: 2,
    level: '200',
    hours: 25,
    category: 'Technical',
    safetyGate: false,
    description: "Introduces veterinary telehealth concepts including the legal Veterinary-Client-Patient Relationship (VCPR), teletriage protocols, and effective communication via telecommunications. Students learn to assess emergency indicators, identify common client complaints, and analyze telehealth workflows.",
    slug: "veterinary-assistant",
  },
  {
    code: "VET-112",
    title: "Building & Professional Development",
    trackCode: "VET",
    trackTitle: "Veterinary Assistant",
    term: 2,
    level: '200',
    hours: 25,
    category: 'Technical',
    safetyGate: false,
    description: "Focuses on readiness including resume building, interview skills, professional networking, and workplace communication. Students develop the soft skills needed for successful employment in veterinary settings.",
    slug: "veterinary-assistant",
  },
  // ==========================================
  // VTE — Veterinary Technician (16 modules)
  // ==========================================
  {
    code: "VTE-101",
    title: "Veterinary Medicine Profession & Practice",
    trackCode: "VTE",
    trackTitle: "Veterinary Technician",
    term: 1,
    level: '100',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Introduces the veterinary technology profession, scope of practice, professional ethics, and the role of the veterinary technician in the healthcare team. Students explore pathways, regulatory frameworks, and the historical development of veterinary medicine.",
    slug: "veterinary-technician",
  },
  {
    code: "VTE-102",
    title: "Veterinary Anatomy & Physiology",
    trackCode: "VTE",
    trackTitle: "Veterinary Technician",
    term: 1,
    level: '100',
    hours: 50,
    category: 'Technical',
    safetyGate: false,
    description: "Provides study of animal anatomy and physiology across species. Students learn structural organization, body systems, comparative anatomy, and physiological processes with emphasis on clinical relevance to veterinary technology practice.",
    slug: "veterinary-technician",
  },
  {
    code: "VTE-103",
    title: "Veterinary Pharmacy & Pharmacology",
    trackCode: "VTE",
    trackTitle: "Veterinary Technician",
    term: 1,
    level: '100',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers pharmacology principles, drug classifications, mechanisms of action, dosage calculations, and pharmacy management. Students learn about common veterinary pharmaceuticals, controlled substance regulations, adverse drug reactions, and safe medication administration.",
    slug: "veterinary-technician",
  },
  {
    code: "VTE-104",
    title: "Animal Behavior, Handling & Restraint",
    trackCode: "VTE",
    trackTitle: "Veterinary Technician",
    term: 1,
    level: '100',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Teaches animal behavior principles, safe handling, and restraint techniques across species. Students learn species-specific behavioral cues, low-stress handling methods, and safety protocols for working with companion, production, and laboratory animals.",
    slug: "veterinary-technician",
  },
  {
    code: "VTE-105",
    title: "Medical Mathematics & Calculations",
    trackCode: "VTE",
    trackTitle: "Veterinary Technician",
    term: 2,
    level: '200',
    hours: 30,
    category: 'Technical',
    safetyGate: false,
    description: "Covers mathematical applications in veterinary medicine including dosage calculations, fluid therapy rates, anesthetic gas flow rates, and conversions. Students develop proficiency in medical mathematics essential for safe patient care.",
    slug: "veterinary-technician",
  },
  {
    code: "VTE-106",
    title: "Clinical Pathology I: Hematology & Laboratory",
    trackCode: "VTE",
    trackTitle: "Veterinary Technician",
    term: 2,
    level: '200',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Introduces clinical pathology with focus on hematology, urinalysis, and basic laboratory procedures. Students learn sample collection, processing, analysis, and quality control. Includes hematology for veterinary technicians and clinical laboratory techniques.",
    slug: "veterinary-technician",
  },
  {
    code: "VTE-107",
    title: "Medical Nursing for Veterinary Technicians",
    trackCode: "VTE",
    trackTitle: "Veterinary Technician",
    term: 2,
    level: '200',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers medical nursing principles including patient assessment, nursing care plans, fluid therapy, and patient monitoring. Students learn to provide nursing care to hospitalized patients across species.",
    slug: "veterinary-technician",
  },
  {
    code: "VTE-108",
    title: "Nutrition, History & Physical Examination",
    trackCode: "VTE",
    trackTitle: "Veterinary Technician",
    term: 2,
    level: '200',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Teaches nutritional assessment, patient history taking, and physical examination techniques. Students learn to obtain patient histories, perform physical exams, and develop nutritional plans for various life stages and species.",
    slug: "veterinary-technician",
  },
  {
    code: "VTE-109",
    title: "Clinical Pathology II: Microbiology & Parasitology",
    trackCode: "VTE",
    trackTitle: "Veterinary Technician",
    term: 3,
    level: '300',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "clinical pathology covering microbiology, clinical parasitology, cytology, and clinical chemistry. Students learn culture techniques, parasite identification, cytologic evaluation, and diagnostic procedures.",
    slug: "veterinary-technician",
  },
  {
    code: "VTE-110",
    title: "Anesthesia for Veterinary Technicians",
    trackCode: "VTE",
    trackTitle: "Veterinary Technician",
    term: 3,
    level: '300',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers anesthetic principles, agents, monitoring, and recovery. Students learn pre-anesthetic assessment, anesthetic induction and maintenance, patient monitoring during anesthesia, and management of anesthetic complications.",
    slug: "veterinary-technician",
  },
  {
    code: "VTE-111",
    title: "Surgical Nursing for Veterinary Technicians",
    trackCode: "VTE",
    trackTitle: "Veterinary Technician",
    term: 3,
    level: '300',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Teaches surgical nursing including aseptic technique, instrument identification, patient preparation, intraoperative assistance, and postoperative care. Students learn surgical room protocols and the technician's role in surgical procedures.",
    slug: "veterinary-technician",
  },
  {
    code: "VTE-112",
    title: "Radiography & Diagnostic Imaging",
    trackCode: "VTE",
    trackTitle: "Veterinary Technician",
    term: 3,
    level: '300',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers radiographic principles, positioning, exposure techniques, radiation safety, and equipment operation. Students learn to produce diagnostic-quality radiographs and apply radiation safety protocols.",
    slug: "veterinary-technician",
  },
  {
    code: "VTE-113",
    title: "Small & Large Animal Medicine",
    trackCode: "VTE",
    trackTitle: "Veterinary Technician",
    term: 4,
    level: '400',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers medical and nursing care for small and large animal species including farm animal medicine and nursing techniques. Students learn species-specific diseases, treatment protocols, and husbandry practices for production and companion animals.",
    slug: "veterinary-technician",
  },
  {
    code: "VTE-114",
    title: "Animal Nutrition, Reproduction, Genetics & Aging",
    trackCode: "VTE",
    trackTitle: "Veterinary Technician",
    term: 4,
    level: '400',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers animal nutrition, reproductive physiology, genetics, and geriatric care. Students learn life-stage nutrition, breeding management, genetic principles, and care of aging animals including laboratory animal medicine.",
    slug: "veterinary-technician",
  },
  {
    code: "VTE-115",
    title: "Emergency & Wound Care",
    trackCode: "VTE",
    trackTitle: "Veterinary Technician",
    term: 4,
    level: '400',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers emergency medicine, critical care nursing, wound management, and physical therapy. Students learn triage, emergency procedures, wound assessment and treatment, and rehabilitation techniques.",
    slug: "veterinary-technician",
  },
  {
    code: "VTE-116",
    title: "Veterinary Practice Administration & Communications",
    trackCode: "VTE",
    trackTitle: "Veterinary Technician",
    term: 4,
    level: '400',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers veterinary practice management, office procedures, client communications, and professional skills. Students learn practice management software, human resources basics, marketing, and effective communication with clients and colleagues.",
    slug: "veterinary-technician",
  },
  // ==========================================
  // VST — Veterinary Surgical Technician (12 modules)
  // ==========================================
  {
    code: "VST-101",
    title: "Aseptic Technique & Sterilization",
    trackCode: "VST",
    trackTitle: "Veterinary Surgical Technician",
    term: 1,
    level: '100',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "coverage of aseptic technique, sterilization methods, and infection prevention in the surgical setting. Students learn steam sterilization, CDC guidelines for disinfection and sterilization, veterinary infection prevention and control, and sterile field maintenance.",
    slug: "veterinary-surgical-technician",
  },
  {
    code: "VST-102",
    title: "Surgical Instruments & Equipment",
    trackCode: "VST",
    trackTitle: "Veterinary Surgical Technician",
    term: 1,
    level: '100',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers identification, care, and maintenance of surgical instruments and equipment. Students learn procedure-specific instrumentation, surgical instrument care and sterilization methods, and the use of veterinary instruments and equipment references.",
    slug: "veterinary-surgical-technician",
  },
  {
    code: "VST-103",
    title: "Patient Preparation & Positioning",
    trackCode: "VST",
    trackTitle: "Veterinary Surgical Technician",
    term: 1,
    level: '100',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Teaches patient preparation for surgery including clipping, surgical scrub, patient positioning, and surgical patient care. Students learn species-specific positioning techniques and pre-surgical assessment protocols.",
    slug: "veterinary-surgical-technician",
  },
  {
    code: "VST-104",
    title: "Scrub & Circulating Nurse Duties",
    trackCode: "VST",
    trackTitle: "Veterinary Surgical Technician",
    term: 2,
    level: '200',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers the roles and responsibilities of scrub and circulating nurses in veterinary surgery. Students learn gowning and gloving, sterile field maintenance, intraoperative assistance, and circulating nurse duties including monitoring and documentation.",
    slug: "veterinary-surgical-technician",
  },
  {
    code: "VST-105",
    title: "Surgical Care Expertise & Wound Management",
    trackCode: "VST",
    trackTitle: "Veterinary Surgical Technician",
    term: 2,
    level: '200',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers postoperative care, bandaging, wound management, and wound closure techniques. Students learn Ethicon wound closure principles, bandaging techniques, wound assessment, and management of surgical complications.",
    slug: "veterinary-surgical-technician",
  },
  {
    code: "VST-106",
    title: "Pharmacology & Laboratory for Surgical Nursing",
    trackCode: "VST",
    trackTitle: "Veterinary Surgical Technician",
    term: 2,
    level: '200',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers pharmacology and laboratory procedures relevant to surgical nursing. Students learn practical pharmacology, pre-surgical laboratory diagnostics, and medication management in the perioperative period.",
    slug: "veterinary-surgical-technician",
  },
  {
    code: "VST-107",
    title: "Anesthesia & Pain Management",
    trackCode: "VST",
    trackTitle: "Veterinary Surgical Technician",
    term: 2,
    level: '200',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers anesthetic principles and pain management for surgical patients. Students learn anesthetic protocols, monitoring, analgesia techniques, and multimodal pain management strategies.",
    slug: "veterinary-surgical-technician",
  },
  {
    code: "VST-108",
    title: "Surgical Techniques & Procedures",
    trackCode: "VST",
    trackTitle: "Veterinary Surgical Technician",
    term: 3,
    level: '300',
    hours: 50,
    category: 'Technical',
    safetyGate: false,
    description: "Covers surgical techniques including small animal laparoscopy, canine and feline surgical principles, and small animal surgery techniques. Students learn to assist with complex surgical procedures and manage surgical complications.",
    slug: "veterinary-surgical-technician",
  },
  {
    code: "VST-109",
    title: "Diagnostic Imaging & Radiography",
    trackCode: "VST",
    trackTitle: "Veterinary Surgical Technician",
    term: 3,
    level: '300',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers diagnostic imaging relevant to surgical practice including Lavin's radiography, dental radiography, and radiation safety. Students learn to produce and evaluate diagnostic images for surgical planning.",
    slug: "veterinary-surgical-technician",
  },
  {
    code: "VST-110",
    title: "Emergency Critical Care & Specialized Medicine",
    trackCode: "VST",
    trackTitle: "Veterinary Surgical Technician",
    term: 3,
    level: '300',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers emergency and critical care nursing in surgical contexts, plus specialized medical disciplines including cardiology, internal medicine, neurology, oncology, ophthalmology, and orthopedics. Students learn to manage surgical emergencies and support specialized procedures.",
    slug: "veterinary-surgical-technician",
  },
  {
    code: "VST-111",
    title: "Exotic Animal Medicine & Physical Rehabilitation",
    trackCode: "VST",
    trackTitle: "Veterinary Surgical Technician",
    term: 3,
    level: '300',
    hours: 30,
    category: 'Technical',
    safetyGate: false,
    description: "Covers exotic animal surgical considerations and physical rehabilitation. Students learn species-specific surgical needs of exotic animals and postoperative rehabilitation techniques.",
    slug: "veterinary-surgical-technician",
  },
  {
    code: "VST-112",
    title: "Professional Practice, Communications & Compliance",
    trackCode: "VST",
    trackTitle: "Veterinary Surgical Technician",
    term: 3,
    level: '300',
    hours: 25,
    category: 'Technical',
    safetyGate: false,
    description: "Covers professional communication, client service, compliance, and regulatory requirements in surgical practice. Students learn client communications, education, preventive healthcare, professional veterinary ethics, medical record documentation, and team collaboration.",
    slug: "veterinary-surgical-technician",
  },
  // ==========================================
  // VPM — Veterinary Practice Management (8 modules)
  // ==========================================
  {
    code: "VPM-101",
    title: "Business Orientation & Professional Development",
    trackCode: "VPM",
    trackTitle: "Veterinary Practice Management",
    term: 1,
    level: '100',
    hours: 30,
    category: 'Technical',
    safetyGate: false,
    description: "Orients students to business principles and online learning strategies. Students develop skills for confident, independent learning and analyze the interdependent goals of life and business, including the steps needed to achieve them.",
    slug: "veterinary-practice-management",
  },
  {
    code: "VPM-102",
    title: "Principles of Management",
    trackCode: "VPM",
    trackTitle: "Veterinary Practice Management",
    term: 1,
    level: '100',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers fundamental management principles including planning, organizing, leading, and controlling. Students learn management theory, organizational behavior, decision-making processes, and leadership styles applicable to veterinary practice.",
    slug: "veterinary-practice-management",
  },
  {
    code: "VPM-103",
    title: "Basic Accounting for Veterinary Practices",
    trackCode: "VPM",
    trackTitle: "Veterinary Practice Management",
    term: 1,
    level: '100',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Introduces accounting principles relevant to veterinary practice management. Students learn financial statements, bookkeeping, payroll, accounts receivable/payable, and financial analysis for veterinary businesses.",
    slug: "veterinary-practice-management",
  },
  {
    code: "VPM-104",
    title: "Veterinary Practice Management",
    trackCode: "VPM",
    trackTitle: "Veterinary Practice Management",
    term: 2,
    level: '200',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers veterinary practice management including workflow optimization, inventory management, regulatory compliance, and quality assurance. Students learn to manage all aspects of veterinary practice operations.",
    slug: "veterinary-practice-management",
  },
  {
    code: "VPM-105",
    title: "Human Resource Management",
    trackCode: "VPM",
    trackTitle: "Veterinary Practice Management",
    term: 2,
    level: '200',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers HR principles including recruitment, training, performance evaluation, compensation, labor law compliance, and team development. Students learn to build and manage effective veterinary healthcare teams.",
    slug: "veterinary-practice-management",
  },
  {
    code: "VPM-106",
    title: "Marketing for Veterinary Practices",
    trackCode: "VPM",
    trackTitle: "Veterinary Practice Management",
    term: 2,
    level: '200',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers marketing principles and strategies for veterinary practices. Students learn market analysis, brand development, digital marketing, client acquisition and retention, and community outreach strategies.",
    slug: "veterinary-practice-management",
  },
  {
    code: "VPM-107",
    title: "Business Ethics & Professional Conduct",
    trackCode: "VPM",
    trackTitle: "Veterinary Practice Management",
    term: 3,
    level: '300',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers ethical decision-making in veterinary business contexts. Students learn ethical frameworks, corporate social responsibility, professional conduct standards, and the intersection of ethics and business strategy in veterinary medicine.",
    slug: "veterinary-practice-management",
  },
  {
    code: "VPM-108",
    title: "Veterinary Practice Operations Strategy",
    trackCode: "VPM",
    trackTitle: "Veterinary Practice Management",
    term: 3,
    level: '300',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "course integrating all program coursework into a veterinary practice management project. Students develop a complete practice business plan including financial projections, staffing models, marketing strategies, and operational protocols.",
    slug: "veterinary-practice-management",
  },
  // ==========================================
  // VTN — Veterinary Technology (10 modules)
  // ==========================================
  {
    code: "VTN-101",
    title: "Veterinary Pharmacology",
    trackCode: "VTN",
    trackTitle: "Veterinary Technology",
    term: 1,
    level: '100',
    hours: 50,
    category: 'Technical',
    safetyGate: false,
    description: "study of veterinary pharmacology including pharmacokinetics, pharmacodynamics, drug interactions, compounding, and therapeutic protocols. Students explore emerging pharmaceuticals and evidence-based pharmacotherapy.",
    slug: "veterinary-technology",
  },
  {
    code: "VTN-102",
    title: "Understanding the Human-Animal Bond",
    trackCode: "VTN",
    trackTitle: "Veterinary Technology",
    term: 1,
    level: '100',
    hours: 30,
    category: 'Technical',
    safetyGate: false,
    description: "Explores the psychological, social, and emotional dimensions of the human-animal bond. Students learn about attachment theory, grief and bereavement support, animal-assisted therapy, and the role of the bond in veterinary practice.",
    slug: "veterinary-technology",
  },
  {
    code: "VTN-103",
    title: "Safety & Regulatory Compliance in Veterinary Medicine",
    trackCode: "VTN",
    trackTitle: "Veterinary Technology",
    term: 1,
    level: '100',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers safety and regulatory frameworks in veterinary medicine. Students learn OSHA compliance, radiation safety, hazardous material handling, controlled substance regulations, and facility accreditation standards.",
    slug: "veterinary-technology",
  },
  {
    code: "VTN-104",
    title: "Research in Veterinary Technology",
    trackCode: "VTN",
    trackTitle: "Veterinary Technology",
    term: 2,
    level: '200',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Introduces research methodologies applicable to veterinary technology. Students learn evidence-based medicine principles, literature evaluation, research design, data analysis, and critical appraisal of veterinary research.",
    slug: "veterinary-technology",
  },
  {
    code: "VTN-105",
    title: "Preventative Healthcare & Integrative Medicine for Animals",
    trackCode: "VTN",
    trackTitle: "Veterinary Technology",
    term: 2,
    level: '200',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers preventative healthcare strategies and integrative medicine approaches. Students learn wellness protocols, vaccination programs, nutrition, complementary therapies, and holistic approaches to animal health.",
    slug: "veterinary-technology",
  },
  {
    code: "VTN-106",
    title: "Veterinary Practice Management",
    trackCode: "VTN",
    trackTitle: "Veterinary Technology",
    term: 2,
    level: '200',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "practice management for veterinary technology leaders. Students learn strategic planning, quality improvement, team leadership, financial management, and regulatory compliance in practice settings.",
    slug: "veterinary-technology",
  },
  {
    code: "VTN-107",
    title: "Animal Medicine & Domestic Animal Species Nursing",
    trackCode: "VTN",
    trackTitle: "Veterinary Technology",
    term: 3,
    level: '300',
    hours: 50,
    category: 'Technical',
    safetyGate: false,
    description: "study of animal medicine and nursing across domestic species. Students learn complex medical cases, species-specific disease management, nursing interventions, and critical care for diverse domestic animal species.",
    slug: "veterinary-technology",
  },
  {
    code: "VTN-108",
    title: "Veterinary Emergency & Critical Care",
    trackCode: "VTN",
    trackTitle: "Veterinary Technology",
    term: 3,
    level: '300',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "emergency and critical care for veterinary technicians. Students learn triage, emergency procedures, critical care monitoring, life support, trauma management, and disaster preparedness.",
    slug: "veterinary-technology",
  },
  {
    code: "VTN-109",
    title: "Animal Anesthesia & Surgical Nursing",
    trackCode: "VTN",
    trackTitle: "Veterinary Technology",
    term: 4,
    level: '400',
    hours: 50,
    category: 'Technical',
    safetyGate: false,
    description: "anesthesia and surgical nursing for veterinary technology specialists. Students learn anesthetic protocols, complex surgical assistance, perioperative critical care, and anesthesia for high-risk patients.",
    slug: "veterinary-technology",
  },
  {
    code: "VTN-110",
    title: "Clinical Practicum & Portfolio",
    trackCode: "VTN",
    trackTitle: "Veterinary Technology",
    term: 4,
    level: '400',
    hours: 60,
    category: 'Technical',
    safetyGate: false,
    practicum: true,
    description: "practicum integrating all coursework through supervised clinical experiences. Students complete a professional portfolio demonstrating competency across all program domains and present a project.",
    slug: "veterinary-technology",
  },
  // ==========================================
  // PVM — Pre-Veterinary Medicine (13 modules)
  // ==========================================
  {
    code: "PVM-101",
    title: "The Language of Veterinary Medicine & Mathematical Calculations",
    trackCode: "PVM",
    trackTitle: "Pre-Veterinary Medicine",
    term: 1,
    level: '100',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Foundational course covering veterinary medical terminology, mathematical calculations, and the conceptual language of veterinary medicine. Students master the vocabulary and quantitative skills essential for veterinary study.",
    slug: "pre-veterinary-medicine",
  },
  {
    code: "PVM-102",
    title: "Small Animal Internal Medicine & Hematology Part One",
    trackCode: "PVM",
    trackTitle: "Pre-Veterinary Medicine",
    term: 1,
    level: '100',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Introduces small animal internal medicine and hematology. Students learn disease processes, diagnostic approaches, hematologic evaluation, and treatment planning for small animal patients.",
    slug: "pre-veterinary-medicine",
  },
  {
    code: "PVM-103",
    title: "Small Animal Anesthesia: Perioperative to Recovery",
    trackCode: "PVM",
    trackTitle: "Pre-Veterinary Medicine",
    term: 1,
    level: '100',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "coverage of small animal anesthesia from perioperative planning through recovery. Students learn patient preparation, pharmacology, life stage considerations, and anesthetic monitoring and management.",
    slug: "pre-veterinary-medicine",
  },
  {
    code: "PVM-104",
    title: "Radiology & Diagnostic Imaging",
    trackCode: "PVM",
    trackTitle: "Pre-Veterinary Medicine",
    term: 2,
    level: '200',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers radiographic interpretation and diagnostic imaging across body systems. Students learn radiology of the abdomen, parenchymatous organs, esophagus, stomach, respiratory and cardiovascular systems, and bone lesions and fractures.",
    slug: "pre-veterinary-medicine",
  },
  {
    code: "PVM-105",
    title: "Dental Basics &  Dental Problems",
    trackCode: "PVM",
    trackTitle: "Pre-Veterinary Medicine",
    term: 2,
    level: '200',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers dental fundamentals and dental problem-solving. Students learn dental anatomy, oral examinations, prophylaxis, dental radiography, and root cause analysis of dental problems.",
    slug: "pre-veterinary-medicine",
  },
  {
    code: "PVM-106",
    title: "Fluid Therapy, Transfusion Medicine & the Surgical Suite",
    trackCode: "PVM",
    trackTitle: "Pre-Veterinary Medicine",
    term: 2,
    level: '200',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers fluid therapy, transfusion medicine, and surgical suite operations. Students learn fluid therapy planning, blood typing and transfusion protocols, and surgical suite management including the pharmaceutical Rx and medical records.",
    slug: "pre-veterinary-medicine",
  },
  {
    code: "PVM-107",
    title: "Equine Medicine & Core Skills",
    trackCode: "PVM",
    trackTitle: "Pre-Veterinary Medicine",
    term: 2,
    level: '200',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers equine medicine fundamentals and core skills. Students learn the trail to core equine skills, equine emergencies, and species-specific considerations for equine patients.",
    slug: "pre-veterinary-medicine",
  },
  {
    code: "PVM-108",
    title: "Neurology & Cancer in Small Animals",
    trackCode: "PVM",
    trackTitle: "Pre-Veterinary Medicine",
    term: 3,
    level: '300',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers neurologic disorders and oncology in small animal practice. Students learn neurologic examinations, cancer diagnosis and treatment, and management of neurologic and oncologic patients.",
    slug: "pre-veterinary-medicine",
  },
  {
    code: "PVM-109",
    title: "Exotic, Avian & Reptile Medicine",
    trackCode: "PVM",
    trackTitle: "Pre-Veterinary Medicine",
    term: 3,
    level: '300',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers diseases and disorders of companion exotic animals, avian medicine, and reptile/amphibian zoonoses. Students learn species-specific husbandry, disease recognition, and treatment of exotic patients.",
    slug: "pre-veterinary-medicine",
  },
  {
    code: "PVM-110",
    title: "Cardiovascular ECC & Specialized Clinical Procedures",
    trackCode: "PVM",
    trackTitle: "Pre-Veterinary Medicine",
    term: 3,
    level: '300',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers small animal cardiovascular emergency and critical care plus specialized clinical procedures. Students learn cardiovascular ECC, diagnostic procedures, electrocardiogram interpretation, and charting.",
    slug: "pre-veterinary-medicine",
  },
  {
    code: "PVM-111",
    title: "Nutrition, Wellness & Preventive Care",
    trackCode: "PVM",
    trackTitle: "Pre-Veterinary Medicine",
    term: 3,
    level: '300',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "coverage of nutrition, wellness, and preventive healthcare. Students learn about feline nutrition, food hypersensitivity, raw food diets, pet food labels, obesity management, the microbiome, vaccinations, heartworm and vector-borne disease prevention, and senior animal care.",
    slug: "pre-veterinary-medicine",
  },
  {
    code: "PVM-112",
    title: "Clinical Specialties Integration",
    trackCode: "PVM",
    trackTitle: "Pre-Veterinary Medicine",
    term: 4,
    level: '400',
    hours: 50,
    category: 'Technical',
    safetyGate: false,
    description: "Integrative course covering clinical specialties including anesthesiology, behavior, cardiology, emergency and critical care, hospice, hyperbaric oxygen therapy, iodine 131 treatment, internal medicine, interventional radiology, neurology, ophthalmology, sports medicine and rehabilitation, surgery, toxicology,…",
    slug: "pre-veterinary-medicine",
  },
  {
    code: "PVM-113",
    title: "Clinical Integration",
    trackCode: "PVM",
    trackTitle: "Pre-Veterinary Medicine",
    term: 4,
    level: '400',
    hours: 50,
    category: 'Technical',
    safetyGate: false,
    practicum: true,
    description: "course integrating clinical knowledge through case-based learning and presentations. Students analyze complex cases involving otitis, pain recognition, reproductive emergencies, feline infectious peritonitis, continuous glucose monitoring, and other clinical topics.",
    slug: "pre-veterinary-medicine",
  },
  // ==========================================
  // VPT — Veterinary Pathology Technician (12 modules)
  // ==========================================
  {
    code: "VPT-101",
    title: "Foundations of Pathology & Laboratory Safety",
    trackCode: "VPT",
    trackTitle: "Veterinary Pathology Technician",
    term: 1,
    level: '100',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Introduces pathology fundamentals, laboratory safety, and quality assurance. Students learn the rationale for testing procedures, pathophysiology, hazard prevention, MSDS utilization, and the interrelationship between procedures. Includes skills for independent online learning.",
    slug: "veterinary-pathology-technician",
  },
  {
    code: "VPT-102",
    title: "Microscopy & Instrumentation",
    trackCode: "VPT",
    trackTitle: "Veterinary Pathology Technician",
    term: 1,
    level: '100',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers microscope operation, maintenance, and laboratory instrumentation. Students learn parts and functions of the microscope, proper maintenance and cleaning, centrifuge calibration, instrument troubleshooting, and instrumentation selection criteria.",
    slug: "veterinary-pathology-technician",
  },
  {
    code: "VPT-103",
    title: "Hematology Fundamentals",
    trackCode: "VPT",
    trackTitle: "Veterinary Pathology Technician",
    term: 1,
    level: '100',
    hours: 50,
    category: 'Technical',
    safetyGate: false,
    description: "study of veterinary hematology including manual and automated methodologies, specimen collection, hematopoiesis, erythropoiesis, leukocyte function, anemias, cell morphology, and exotic hematology. Students learn to perform and interpret hematologic tests.",
    slug: "veterinary-pathology-technician",
  },
  {
    code: "VPT-104",
    title: "Clinical Chemistry",
    trackCode: "VPT",
    trackTitle: "Veterinary Pathology Technician",
    term: 2,
    level: '200',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers clinical chemistry including wellness, pre-surgical, disease-specific, and organ-specific profiles. Students learn automated and point-of-care methodologies, species-specific tests, and the relationship between tests and organ systems or diseases.",
    slug: "veterinary-pathology-technician",
  },
  {
    code: "VPT-105",
    title: "Urinalysis & Coagulation",
    trackCode: "VPT",
    trackTitle: "Veterinary Pathology Technician",
    term: 2,
    level: '200',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers urinalysis and coagulation testing. Students learn reagent strip usage, interferences, culture indications, renal physiology, coagulation disorders (thrombocytopenia, DIC, von Willebrands, anticoagulant toxicosis), and hemostasis pathways.",
    slug: "veterinary-pathology-technician",
  },
  {
    code: "VPT-106",
    title: "Cytology & Immuno-Hematology",
    trackCode: "VPT",
    trackTitle: "Veterinary Pathology Technician",
    term: 2,
    level: '200',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers cytologic evaluation and immuno-hematology. Students learn collection methods, basic cell type identification, blood typing and grouping, transfusion principles, donor selection, and specimen handling for blood typing.",
    slug: "veterinary-pathology-technician",
  },
  {
    code: "VPT-107",
    title: "Serology, Immunology & Endocrinology",
    trackCode: "VPT",
    trackTitle: "Veterinary Pathology Technician",
    term: 3,
    level: '300',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers serological testing, immunology, and endocrinology. Students learn complement fixation, immunofluorescence, PCR/DNA amplification, antibody titers, diagnostic tests for Addison's, Cushing's, diabetes, and thyroid disorders, and reproductive cycle staging.",
    slug: "veterinary-pathology-technician",
  },
  {
    code: "VPT-108",
    title: "Microbiology & Parasitology",
    trackCode: "VPT",
    trackTitle: "Veterinary Pathology Technician",
    term: 3,
    level: '300',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers microbiological culture techniques and veterinary parasitology. Students learn aerobic, anaerobic, blood, fungal, and fecal cultures, internal and external parasite identification, life cycles, diseases, prevention, treatment, and anthelmintic resistance.",
    slug: "veterinary-pathology-technician",
  },
  {
    code: "VPT-109",
    title: "Toxicology & Acid-Base Evaluation",
    trackCode: "VPT",
    trackTitle: "Veterinary Pathology Technician",
    term: 3,
    level: '300',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers veterinary toxicology and acid-base evaluation. Students learn common toxic agents, specimen shipping for toxicology, drug screening, venous vs. arterial sample evaluation, blood gas handling, acid-base disorders, and anion gap measurement.",
    slug: "veterinary-pathology-technician",
  },
  {
    code: "VPT-110",
    title: "Quality Assurance & Reference Intervals",
    trackCode: "VPT",
    trackTitle: "Veterinary Pathology Technician",
    term: 4,
    level: '400',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "quality assurance and reference interval management. Students learn reference interval generation, validation, relationship to patient results, and the role of reference intervals as diagnostic tools for veterinarians.",
    slug: "veterinary-pathology-technician",
  },
  {
    code: "VPT-111",
    title: "Specimen Management & Laboratory Operations",
    trackCode: "VPT",
    trackTitle: "Veterinary Pathology Technician",
    term: 4,
    level: '400',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers specimen collection, handling, storage, shipping, and specialized laboratory procedures. Students learn species-specific pre- and post-analytic care, low-stress restraint, protein electrophoresis, urinary calculi handling, and reference laboratory submission criteria.",
    slug: "veterinary-pathology-technician",
  },
  {
    code: "VPT-112",
    title: "Clinical Pathology Practicum &",
    trackCode: "VPT",
    trackTitle: "Veterinary Pathology Technician",
    term: 4,
    level: '400',
    hours: 50,
    category: 'Technical',
    safetyGate: false,
    practicum: true,
    description: "practicum integrating all pathology coursework through supervised laboratory experiences. Students demonstrate competency in all laboratory disciplines and present a case study integrating multiple diagnostic modalities.",
    slug: "veterinary-pathology-technician",
  },
  // ==========================================
  // EQN — Equine Nursing Technicians (9 modules)
  // ==========================================
  {
    code: "EQN-101",
    title: "Equine Veterinary Nursing Foundations & Terminology",
    trackCode: "EQN",
    trackTitle: "Equine Nursing Technicians",
    term: 1,
    level: '100',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Introduces equine veterinary nursing, terminology, and the foundational skills needed for confident independent online learning. Students learn equine-specific medical terminology, the scope of equine veterinary nursing, and core professional competencies.",
    slug: "equine-nursing-technicians",
  },
  {
    code: "EQN-102",
    title: "Horse Anatomy & Digestive System",
    trackCode: "EQN",
    trackTitle: "Equine Nursing Technicians",
    term: 1,
    level: '100',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers equine anatomy and the digestive system in detail. Students learn the anatomical structures of the horse, digestive physiology, and the unique features of the equine gastrointestinal system.",
    slug: "equine-nursing-technicians",
  },
  {
    code: "EQN-103",
    title: "Equine Anesthesia, Monitoring & Emergency Therapy",
    trackCode: "EQN",
    trackTitle: "Equine Nursing Technicians",
    term: 1,
    level: '100',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers equine anesthesia, monitoring, and emergency therapy. Students learn anesthetic protocols for horses, MAC (minimum alveolar concentration), acepromazine use, monitoring techniques, and emergency therapeutic interventions.",
    slug: "equine-nursing-technicians",
  },
  {
    code: "EQN-104",
    title: "Equine Medicine & Disease Management",
    trackCode: "EQN",
    trackTitle: "Equine Nursing Technicians",
    term: 2,
    level: '200',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers equine medicine including common diseases, infectious agents, and metabolic conditions. Students learn about PPID vs ESM, clostridium, e-coli, salmonella, Rhodococcus, OCD lesions, myoglobinuria, and hemoprotein disorders.",
    slug: "equine-nursing-technicians",
  },
  {
    code: "EQN-105",
    title: "Equine Lameness, Neurology & Diagnostic Examination",
    trackCode: "EQN",
    trackTitle: "Equine Nursing Technicians",
    term: 2,
    level: '200',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers equine lameness evaluation, neurologic examination, and cranial nerve assessment. Students learn lameness diagnosis, the neurologic examination process, vagus nerve and cranial nerve evaluation, laryngeal hemiplegia, and endophyte-related conditions.",
    slug: "equine-nursing-technicians",
  },
  {
    code: "EQN-106",
    title: "Equine Nursing Techniques & Large Animal Procedures",
    trackCode: "EQN",
    trackTitle: "Equine Nursing Technicians",
    term: 2,
    level: '200',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers equine nursing techniques and large animal clinical procedures. Students learn neonatology medicine and surgery, vaccination guidelines, internal parasite control, feeding and care of horses, age determination, and common veterinary drug administration.",
    slug: "equine-nursing-technicians",
  },
  {
    code: "EQN-107",
    title: "Radiographic Examinations & Diagnostic Imaging",
    trackCode: "EQN",
    trackTitle: "Equine Nursing Technicians",
    term: 3,
    level: '300',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers radiographic examination techniques and diagnostic imaging for equine patients. Students learn positioning, exposure techniques, radiation safety, and interpretation of equine radiographic studies.",
    slug: "equine-nursing-technicians",
  },
  {
    code: "EQN-108",
    title: "Equine Emergencies & Critical Care",
    trackCode: "EQN",
    trackTitle: "Equine Nursing Technicians",
    term: 3,
    level: '300',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers equine emergency medicine and critical care nursing. Students learn triage, emergency procedures, critical care monitoring, and management of equine emergencies including colic, trauma, and dystocia.",
    slug: "equine-nursing-technicians",
  },
  {
    code: "EQN-109",
    title: "Clinical Practicum &",
    trackCode: "EQN",
    trackTitle: "Equine Nursing Technicians",
    term: 3,
    level: '300',
    hours: 50,
    category: 'Technical',
    safetyGate: false,
    practicum: true,
    description: "practicum integrating all equine nursing coursework through supervised clinical experiences. Students demonstrate competency in equine veterinary nursing and present a case study.",
    slug: "equine-nursing-technicians",
  },
  // ==========================================
  // GRO — Pet Grooming (7 modules)
  // ==========================================
  {
    code: "GRO-101",
    title: "Introduction to Grooming & Pet Safety",
    trackCode: "GRO",
    trackTitle: "Pet Grooming",
    term: 1,
    level: '100',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Introduces pet grooming fundamentals, safety protocols, and animal welfare. Students learn the historical background of dogs and cats, safety tools, sanitation processes, CPR and first aid techniques, and the fundamentals of the grooming profession.",
    slug: "pet-grooming",
  },
  {
    code: "GRO-102",
    title: "Canine Knowledge, Breed Profiles & Development",
    trackCode: "GRO",
    trackTitle: "Pet Grooming",
    term: 1,
    level: '100',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers canine breed recognition, characteristics, and development. Students learn AKC breed groups, breed-specific grooming needs, dog development stages, personality types, and how each personality handles the grooming process.",
    slug: "pet-grooming",
  },
  {
    code: "GRO-103",
    title: "Equipment, Tools & Product Knowledge",
    trackCode: "GRO",
    trackTitle: "Pet Grooming",
    term: 1,
    level: '100',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers grooming equipment selection, use, and maintenance. Students learn to select, use, and maintain clippers, scissors, brushes, combs, drying equipment, and grooming products. Includes coat and skin care fundamentals.",
    slug: "pet-grooming",
  },
  {
    code: "GRO-104",
    title: "Bathing, Brushing & Drying Techniques",
    trackCode: "GRO",
    trackTitle: "Pet Grooming",
    term: 2,
    level: '200',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers bathing, brushing, and drying techniques. Students learn preparation steps for grooming, bathing procedures, drying methods including fluff drying, ear cleaning, nail cutting, pad cleaning, and private area cleaning.",
    slug: "pet-grooming",
  },
  {
    code: "GRO-105",
    title: "Breed-Specific Grooming & Styling Techniques",
    trackCode: "GRO",
    trackTitle: "Pet Grooming",
    term: 2,
    level: '200',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers breed-specific grooming procedures across all AKC groups. Students learn grooming procedures for terriers, sporting, herding, hound, working, toy, and nonsporting groups, plus poodle grooming, mixed breed styling, and puppy grooming.",
    slug: "pet-grooming",
  },
  {
    code: "GRO-106",
    title: "Grooming Safety, Injury Prevention & Self-Care",
    trackCode: "GRO",
    trackTitle: "Pet Grooming",
    term: 2,
    level: '200',
    hours: 30,
    category: 'Technical',
    safetyGate: false,
    description: "Covers grooming safety, injury prevention, and groomer self-care. Students learn safety protocols, injury prevention techniques, handling difficult dogs, and strategies for preventing physical strain and injury in the grooming profession.",
    slug: "pet-grooming",
  },
  {
    code: "GRO-107",
    title: "Customer Relations & Mobile Grooming Operations",
    trackCode: "GRO",
    trackTitle: "Pet Grooming",
    term: 2,
    level: '200',
    hours: 25,
    category: 'Technical',
    safetyGate: false,
    description: "Covers customer service and mobile grooming operations. Students learn client communication, customer relations, mobile grooming business operations, and the practical aspects of running a grooming service.",
    slug: "pet-grooming",
  },
  // ==========================================
  // FEL — Felines & Health (6 modules)
  // ==========================================
  {
    code: "FEL-101",
    title: "Feline Foundations: Overview, Breeds & Temperament",
    trackCode: "FEL",
    trackTitle: "Felines & Health",
    term: 1,
    level: '100',
    hours: 25,
    category: 'Technical',
    safetyGate: false,
    description: "Introduces the fundamentals of feline care including breed identification, temperament assessment, and handling. Students learn cat breeds, personality traits, characteristics, and appropriate handling methods for cats.",
    slug: "felines-and-health",
  },
  {
    code: "FEL-102",
    title: "Learning Theories & the Feline Mind",
    trackCode: "FEL",
    trackTitle: "Felines & Health",
    term: 1,
    level: '100',
    hours: 30,
    category: 'Technical',
    safetyGate: false,
    description: "Explores feline cognition, learning theories, and behavior modification. Students learn how cats learn, behavior modification products, and essential cat care items for training and enrichment.",
    slug: "felines-and-health",
  },
  {
    code: "FEL-103",
    title: "Cat Behavior Management & Basic Training",
    trackCode: "FEL",
    trackTitle: "Felines & Health",
    term: 1,
    level: '100',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers cat behavior management, basic training techniques, and addressing unwanted behaviors. Students learn behavior modification strategies, preventing unwanted behaviors, and shelter experience protocols.",
    slug: "felines-and-health",
  },
  {
    code: "FEL-104",
    title: "Cat Nutrition & Basic Care",
    trackCode: "FEL",
    trackTitle: "Felines & Health",
    term: 1,
    level: '100',
    hours: 25,
    category: 'Technical',
    safetyGate: false,
    description: "Covers feline nutrition, basic care, and health management. Students learn species-appropriate nutrition, feeding strategies, routine care protocols, and recognizing common health concerns in cats.",
    slug: "felines-and-health",
  },
  {
    code: "FEL-105",
    title: "Feline Grooming: Handling, Bathing & Drying",
    trackCode: "FEL",
    trackTitle: "Felines & Health",
    term: 1,
    level: '100',
    hours: 30,
    category: 'Technical',
    safetyGate: false,
    description: "Covers feline grooming procedures including handling, bathing, drying, and styling. Students learn cat-specific grooming techniques, safety concerns, and practical methods for grooming cats and kittens.",
    slug: "felines-and-health",
  },
  {
    code: "FEL-106",
    title: "Safety, First Aid & Shelter Experience",
    trackCode: "FEL",
    trackTitle: "Felines & Health",
    term: 1,
    level: '100',
    hours: 25,
    category: 'Technical',
    safetyGate: false,
    description: "Covers feline safety protocols, first aid techniques, and shelter experience. Students learn pet CPR, first aid certification, safety practices, and shelter handling procedures specific to cats.",
    slug: "felines-and-health",
  },
  // ==========================================
  // ZKA — Zookeeper Assistant (9 modules)
  // ==========================================
  {
    code: "ZKA-101",
    title: "Introduction to Zoos & Zookeeping",
    trackCode: "ZKA",
    trackTitle: "Zookeeper Assistant",
    term: 1,
    level: '100',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Introduces the zookeeping profession, zoo operations, and the role of the zookeeper assistant. Students learn the history and purpose of zoos, zoo organizational structures, and pathways in zookeeping.",
    slug: "zookeeper-assistant",
  },
  {
    code: "ZKA-102",
    title: "Exotic Animal Housing, Exhibits & Husbandry",
    trackCode: "ZKA",
    trackTitle: "Zookeeper Assistant",
    term: 1,
    level: '100',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers exotic animal housing, exhibit design, and daily husbandry routines. Students learn species-appropriate enclosure requirements, environmental enrichment, sanitation protocols, and daily care routines for diverse species.",
    slug: "zookeeper-assistant",
  },
  {
    code: "ZKA-103",
    title: "Animal Health & Zookeeping Safety",
    trackCode: "ZKA",
    trackTitle: "Zookeeper Assistant",
    term: 1,
    level: '100',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers animal health monitoring and safety protocols in zoo settings. Students learn health assessment, disease prevention, zoonotic disease awareness, workplace safety, and emergency response procedures.",
    slug: "zookeeper-assistant",
  },
  {
    code: "ZKA-104",
    title: "Exotic Animal Behavior, Enrichment & Training",
    trackCode: "ZKA",
    trackTitle: "Zookeeper Assistant",
    term: 2,
    level: '200',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers exotic animal behavior, environmental enrichment, and training techniques. Students learn species-specific behavior patterns, enrichment program design, positive reinforcement training, and behavioral assessment.",
    slug: "zookeeper-assistant",
  },
  {
    code: "ZKA-105",
    title: "Zoo Conservation & Breeding Programs",
    trackCode: "ZKA",
    trackTitle: "Zookeeper Assistant",
    term: 2,
    level: '200',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers zoo-based conservation programs and captive breeding. Students learn Species Survival Plans, conservation genetics, population management, and the role of zoos in global conservation efforts.",
    slug: "zookeeper-assistant",
  },
  {
    code: "ZKA-106",
    title: "Biology & Taxonomy of Zoo Species",
    trackCode: "ZKA",
    trackTitle: "Zookeeper Assistant",
    term: 2,
    level: '200',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers the biology and taxonomy of major animal groups represented in zoos. Students learn ornithology, ichthyology, mammalogy, herpetology, entomology, general parasitology, genetics, comparative anatomy, and vertebrate physiology.",
    slug: "zookeeper-assistant",
  },
  {
    code: "ZKA-107",
    title: "Ecology & Conservation Science",
    trackCode: "ZKA",
    trackTitle: "Zookeeper Assistant",
    term: 3,
    level: '300',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers ecological principles and conservation science relevant to zookeeping. Students learn marine and freshwater ecology, disease ecology, tropical ecology, biogeography, paleobiology, wildland fire ecology, and ecological restoration.",
    slug: "zookeeper-assistant",
  },
  {
    code: "ZKA-108",
    title: "Wildlife Management, Policy & Visitor Education",
    trackCode: "ZKA",
    trackTitle: "Zookeeper Assistant",
    term: 3,
    level: '300',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers wildlife management, conservation policy, and zoo visitor education. Students learn fisheries and wildlife law, conservation management for herpetofauna, avian, and mammal species, parks and protected areas management, environmental interpretation, and effective communication of environmental science.",
    slug: "zookeeper-assistant",
  },
  {
    code: "ZKA-109",
    title: "Veterinary Medicine in Zoological Settings &",
    trackCode: "ZKA",
    trackTitle: "Zookeeper Assistant",
    term: 3,
    level: '300',
    hours: 50,
    category: 'Technical',
    safetyGate: false,
    description: "course covering veterinary medicine in zoological settings and integrating all program coursework. Students learn introductory veterinary anesthesia, zoological medicine, laboratory animal medicine, large/food animal medicine, regulatory medicine, and clinical pathology. Includes specialized medicine topics across…",
    slug: "zookeeper-assistant",
  },
  // ==========================================
  // PRT — Professional Trainer (8 modules)
  // ==========================================
  {
    code: "PRT-101",
    title: "Introduction to Service Dogs & Canine Life",
    trackCode: "PRT",
    trackTitle: "Professional Trainer",
    term: 1,
    level: '100',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Introduces the world of service dogs and canine development. Students learn about the role of service dogs, a dog's life stages, AKC breed recognition and characteristics, equipment and training tools, and the foundations of working with service dog candidates.",
    slug: "professional-trainer",
  },
  {
    code: "PRT-102",
    title: "Foundations of Dog Training & Learning Theory",
    trackCode: "PRT",
    trackTitle: "Professional Trainer",
    term: 1,
    level: '100',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers foundational dog training principles and learning theory. Students learn learning, emotions, and behavior; operant and classical conditioning; reinforcement strategies; and the science of animal learning applied to dog training.",
    slug: "professional-trainer",
  },
  {
    code: "PRT-103",
    title: "Breed Characteristics & Canine Health for Trainers",
    trackCode: "PRT",
    trackTitle: "Professional Trainer",
    term: 1,
    level: '100',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers breed-specific characteristics, teaching strategies, and canine health for trainers. Students learn how breed characteristics affect training approaches, common health considerations, and how to address training problems related to breed traits.",
    slug: "professional-trainer",
  },
  {
    code: "PRT-104",
    title: "Obedience Skills: Basic to",
    trackCode: "PRT",
    trackTitle: "Professional Trainer",
    term: 2,
    level: '200',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers obedience training from basic through on-leash and off-leash skills. Students learn to teach basic obedience, on-leash maneuvers, and off-leash obedience. Includes puppy introduction and behavior problem solving.",
    slug: "professional-trainer",
  },
  {
    code: "PRT-105",
    title: "Task Foundations, Behavior Chains & Behavior Sequences",
    trackCode: "PRT",
    trackTitle: "Professional Trainer",
    term: 2,
    level: '200',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers task training foundations, behavior chains, and behavior sequences for service dogs. Students learn to build complex behavior chains, train specific service tasks, and develop behavior sequences for practical applications.",
    slug: "professional-trainer",
  },
  {
    code: "PRT-106",
    title: "Training Problems, Solutions & Client Management",
    trackCode: "PRT",
    trackTitle: "Professional Trainer",
    term: 2,
    level: '200',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers common training problems and their solutions, plus client management skills. Students learn to diagnose and resolve training issues, communicate effectively with clients, and design private training classes.",
    slug: "professional-trainer",
  },
  {
    code: "PRT-107",
    title: "Behavior Modification & Professional Practice",
    trackCode: "PRT",
    trackTitle: "Professional Trainer",
    term: 2,
    level: '200',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers behavior modification techniques and professional practice standards. Students learn behavior modification and animal handling/training techniques, applied animal behavior science, and clinical applications. Includes LA (Least Invasive, Minimally Aversive) principles.",
    slug: "professional-trainer",
  },
  {
    code: "PRT-108",
    title: "CPR, First Aid & Final Assessment",
    trackCode: "PRT",
    trackTitle: "Professional Trainer",
    term: 2,
    level: '200',
    hours: 25,
    category: 'Technical',
    safetyGate: false,
    description: "Covers canine CPR and first aid techniques, and serves as the program's final assessment. Students learn emergency first aid, CPR certification, and complete a assessment demonstrating proficiency across all program competencies.",
    slug: "professional-trainer",
  },
  // ==========================================
  // ABT — Animal Behavior Technician (9 modules)
  // ==========================================
  {
    code: "ABT-101",
    title: "Foundations of Animal Behavior & Learning Theory",
    trackCode: "ABT",
    trackTitle: "Animal Behavior Technician",
    term: 1,
    level: '100',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "foundation in animal behavior science and learning theory. Students learn ethics and welfare, the human-animal bond, learning theory, operant and classical conditioning, non-associative learning, social learning, extinction, and the LA (Least Invasive, Minimally Aversive) philosophy.",
    slug: "animal-behavior-technician",
  },
  {
    code: "ABT-102",
    title: "Normal Development, Behavior & Observation Across Species",
    trackCode: "ABT",
    trackTitle: "Animal Behavior Technician",
    term: 1,
    level: '100',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers normal development, domestication, animal cognition, and species-specific behavior observation. Students learn normal development and behavior, domestication principles, animal cognition, and observe and identify behaviors across feline, canine, parrot, equine, and exotic species.",
    slug: "animal-behavior-technician",
  },
  {
    code: "ABT-103",
    title: "Neurochemistry & Psychopharmacology",
    trackCode: "ABT",
    trackTitle: "Animal Behavior Technician",
    term: 1,
    level: '100',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers veterinary neurochemistry and psychopharmacology. Students learn neurochemistry and neuro-psychopharmacology, common psychotropic agents (mechanism of action, side effects, dosing, uses), and how to discuss psychotropics with clients.",
    slug: "animal-behavior-technician",
  },
  {
    code: "ABT-104",
    title: "Applied Behavior Modification Techniques",
    trackCode: "ABT",
    trackTitle: "Animal Behavior Technician",
    term: 2,
    level: '200',
    hours: 50,
    category: 'Technical',
    safetyGate: false,
    description: "coverage of applied behavior modification techniques. Students learn operant conditioning quadrants, classical conditioning, desensitization and counter conditioning (DS/CC), shaping, targeting, capturing, luring, fading prompts, the six aspects of fluency, behavior chaining, generalization, and stimulus control.",
    slug: "animal-behavior-technician",
  },
  {
    code: "ABT-105",
    title: "Behavior Problems & Treatment Strategies",
    trackCode: "ABT",
    trackTitle: "Animal Behavior Technician",
    term: 2,
    level: '200',
    hours: 50,
    category: 'Technical',
    safetyGate: false,
    description: "Covers diagnosis and treatment of common behavior problems. Students learn to recognize and address aggression, anxiety, fear, panic, separation anxiety, compulsive disorders, phobias, conspecific and human-directed aggression, motion-triggered reactivity, possession-related aggression, and recognize behavior…",
    slug: "animal-behavior-technician",
  },
  {
    code: "ABT-106",
    title: "Client Communication, Counseling & Professional Skills",
    trackCode: "ABT",
    trackTitle: "Animal Behavior Technician",
    term: 2,
    level: '200',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers client communication, counseling, and professional skills for behavior technicians. Students learn compassionate and active listening, conflict resolution, calming communication, grief counseling, quality of life discussions, interpersonal relationships, and behavioral record keeping.",
    slug: "animal-behavior-technician",
  },
  {
    code: "ABT-107",
    title: "Training Protocols & Problem Prevention",
    trackCode: "ABT",
    trackTitle: "Animal Behavior Technician",
    term: 3,
    level: '300',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers training protocols and problem prevention counseling. Students learn to develop problem prevention counseling plans across ingestive, elimination, confinement, travel, play, social interactions, handling, grooming, medical care, and equipment categories. Includes writing professional reports and developing…",
    slug: "animal-behavior-technician",
  },
  {
    code: "ABT-108",
    title: "Professional Practice, Ethics & LA",
    trackCode: "ABT",
    trackTitle: "Animal Behavior Technician",
    term: 3,
    level: '300',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    description: "Covers professional practice standards, ethics, and the LA philosophy. Students learn professional ethics, LA dedication, species-specific behavior management (appeasement, conflict, displacement, offensive vs. defensive behaviors, non-threatening body language), and professional reporting standards.",
    slug: "animal-behavior-technician",
  },
  {
    code: "ABT-109",
    title: "Clinical Practicum & Portfolio",
    trackCode: "ABT",
    trackTitle: "Animal Behavior Technician",
    term: 3,
    level: '300',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    practicum: true,
    description: "practicum integrating all behavior coursework through supervised clinical experiences. Students demonstrate competency in behavior assessment, modification plan development, client counseling, and present a  portfolio of case studies.",
    slug: "animal-behavior-technician",
  },
  // ==========================================
  // ACA — Animal Care Assistant (7 modules)
  // ==========================================
  {
    code: "ACA-101",
    title: "Introduction to Animal Care & Pet Handling",
    trackCode: "ACA",
    trackTitle: "Animal Care Assistant",
    term: 1,
    level: '100',
    hours: 30,
    category: 'Technical',
    safetyGate: false,
    description: "Introduces fundamental animal care and pet handling skills. Students learn basic animal care procedures, safe handling techniques, sanitation processes, and the foundational knowledge needed for animal care assistant roles.",
    slug: "animal-care-assistant",
  },
  {
    code: "ACA-102",
    title: "AKC Breeds, Recognition & Characteristics",
    trackCode: "ACA",
    trackTitle: "Animal Care Assistant",
    term: 1,
    level: '100',
    hours: 20,
    category: 'Technical',
    safetyGate: false,
    description: "Covers AKC breed recognition and characteristics for animal care assistants. Students learn to identify dog breeds, understand breed-specific traits, and adapt care approaches accordingly.",
    slug: "animal-care-assistant",
  },
  {
    code: "ACA-103",
    title: "Bathing Techniques & Sanitation Process",
    trackCode: "ACA",
    trackTitle: "Animal Care Assistant",
    term: 1,
    level: '100',
    hours: 25,
    category: 'Technical',
    safetyGate: false,
    description: "Covers dog bathing techniques and sanitation processes. Students learn proper bathing methods, sanitation protocols, and hygiene standards for animal care facilities.",
    slug: "animal-care-assistant",
  },
  {
    code: "ACA-104",
    title: "Pet Nutrition, Diet & Pet Care",
    trackCode: "ACA",
    trackTitle: "Animal Care Assistant",
    term: 1,
    level: '100',
    hours: 25,
    category: 'Technical',
    safetyGate: false,
    description: "Covers pet nutrition, diet management, and general pet care. Students learn nutritional requirements, feeding protocols, and pet care practices for various species.",
    slug: "animal-care-assistant",
  },
  {
    code: "ACA-105",
    title: "Pet Massage & Emotional Intelligence",
    trackCode: "ACA",
    trackTitle: "Animal Care Assistant",
    term: 1,
    level: '100',
    hours: 25,
    category: 'Technical',
    safetyGate: false,
    description: "Covers pet massage techniques and emotional intelligence in animal care. Students learn pet massage, emotional intelligence, empathy, active listening, trust building, and conflict management in animal care settings.",
    slug: "animal-care-assistant",
  },
  {
    code: "ACA-106",
    title: "Dog Walking, Day Care & Client Relations",
    trackCode: "ACA",
    trackTitle: "Animal Care Assistant",
    term: 1,
    level: '100',
    hours: 25,
    category: 'Technical',
    safetyGate: false,
    description: "Covers dog walking, doggie day care operations, and client relations. Students learn safe dog walking practices, day care management, and effective client communication for animal care businesses.",
    slug: "animal-care-assistant",
  },
  {
    code: "ACA-107",
    title: "CPR, First Aid & Professional Resilience",
    trackCode: "ACA",
    trackTitle: "Animal Care Assistant",
    term: 1,
    level: '100',
    hours: 20,
    category: 'Technical',
    safetyGate: false,
    description: "Covers pet CPR and first aid techniques, plus professional resilience and decision-making skills. Students learn emergency first aid, CPR certification, adaptive problem-solving, and resilience strategies for animal care professionals.",
    slug: "animal-care-assistant",
  },
  // ==========================================
  // GSP — Grooming Salon Practice Management (9 modules)
  // ==========================================
  {
    code: "GSP-101",
    title: "Grooming Foundations & Salon Operations",
    trackCode: "GSP",
    trackTitle: "Grooming Salon Practice Management",
    term: 1,
    level: '100',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "grooming foundations and salon operations. Students learn dog development, handling, equipment, breed recognition, basic through dog grooming, bathing, drying, sanitation (ANSI/AAMI and CDC standards), and pet care fundamentals.",
    slug: "grooming-salon-practice-management",
  },
  {
    code: "GSP-102",
    title: "Feline Grooming & Multi-Service Practicum",
    trackCode: "GSP",
    trackTitle: "Grooming Salon Practice Management",
    term: 1,
    level: '100',
    hours: 35,
    category: 'Technical',
    safetyGate: false,
    practicum: true,
    description: "Covers feline grooming services and multi-service practicum. Students learn cat breeds, temperament handling, cat bathing and drying, cat grooming procedures, and the integration of multiple services in a grooming salon.",
    slug: "grooming-salon-practice-management",
  },
  {
    code: "GSP-103",
    title: "Business Foundations & Entrepreneurship",
    trackCode: "GSP",
    trackTitle: "Grooming Salon Practice Management",
    term: 1,
    level: '100',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers business foundations and entrepreneurship for pet service businesses. Students learn business models, customer experience design, business planning, daily operations management, service pricing, team building, strategic planning, vendor management, customer retention, risk management, and business launch…",
    slug: "grooming-salon-practice-management",
  },
  {
    code: "GSP-104",
    title: "Marketing & Brand Strategy",
    trackCode: "GSP",
    trackTitle: "Grooming Salon Practice Management",
    term: 2,
    level: '200',
    hours: 50,
    category: 'Technical',
    safetyGate: false,
    description: "marketing and brand strategy for pet service businesses. Students learn brand foundations, customer research, brand voice and visual identity, value propositions, local market analysis, digital marketing, social media management, content production, email and SMS marketing, paid advertising, SEO, local discovery,…",
    slug: "grooming-salon-practice-management",
  },
  {
    code: "GSP-105",
    title: "Technology & AI for Business Operations",
    trackCode: "GSP",
    trackTitle: "Grooming Salon Practice Management",
    term: 2,
    level: '200',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers technology foundations and AI integration for business operations. Students learn digital literacy, cybersecurity, data privacy, AI literacy and prompting, AI tools for operations, customer communication, content production, scheduling, reporting, technology procurement, business dashboards, and technology…",
    slug: "grooming-salon-practice-management",
  },
  {
    code: "GSP-106",
    title: "Financial Management & Regulatory Compliance",
    trackCode: "GSP",
    trackTitle: "Grooming Salon Practice Management",
    term: 2,
    level: '200',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "Covers financial management and regulatory compliance for pet service businesses. Students learn personal and business finance separation, budgeting, banking and payments, financial statements, bookkeeping and payroll with AI, tax strategy and compliance, entity structuring, deductions, sales tax, regulatory…",
    slug: "grooming-salon-practice-management",
  },
  {
    code: "GSP-107",
    title: "Leadership & Professional Development",
    trackCode: "GSP",
    trackTitle: "Grooming Salon Practice Management",
    term: 3,
    level: '300',
    hours: 40,
    category: 'Technical',
    safetyGate: false,
    description: "Covers leadership and professional development for salon managers. Students learn emotional intelligence, relational leadership, empathy, active listening, trust building, feedback and conflict repair, difficult conversations, cultural competence, coaching and motivation, resilience, cognitive biases, critical…",
    slug: "grooming-salon-practice-management",
  },
  {
    code: "GSP-108",
    title: "Salon Business Strategy & Launch",
    trackCode: "GSP",
    trackTitle: "Grooming Salon Practice Management",
    term: 3,
    level: '300',
    hours: 45,
    category: 'Technical',
    safetyGate: false,
    description: "course integrating all program coursework into a grooming salon business strategy. Students develop a complete business plan including operations, marketing, technology, financial, and governance components, and present a final launch-ready business proposal.",
    slug: "grooming-salon-practice-management",
  },
  {
    code: "GSP-109",
    title: "Grooming Skills & Private Class Design",
    trackCode: "GSP",
    trackTitle: "Grooming Salon Practice Management",
    term: 3,
    level: '300',
    hours: 25,
    category: 'Technical',
    safetyGate: false,
    description: "grooming skills and private class design for salon professionals. Students master  grooming techniques, breed-specific styling, mixed-breed and freestyle styling, and learn to design and deliver private grooming classes and final assessments.",
    slug: "grooming-salon-practice-management",
  },
];

// Filter modules by pathway code
export function modulesForTrack(trackCode: string): CatalogModule[] {
  return ALL_CATALOG_MODULES.filter((m) => m.trackCode === trackCode);
}
