import type { MetadataRoute } from "next"
import { SITE_URL } from "@/lib/site-url"

// ---------------------------------------------------------------------------
// /robots.txt — generated by Next.js (MetadataRoute). The static
// public/robots.txt was removed so this file is the single source of truth.
//
//   - Portals, auth doors, and API routes stay out of the index.
//   - /shop/bag is intentionally NOT disallowed: it carries a noindex meta
//     tag instead (a Disallow would hide the noindex signal from Google).
//   - The sitemap line feeds Search Console's discovery.
// ---------------------------------------------------------------------------

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/admin",
          "/admin-login",
          "/access-customer",
          "/access-groomer",
          "/access-frontdesk",
          "/learn",
          "/account",
          "/auth",
          "/api",
        ],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
  }
}
