#!/usr/bin/env node
// ---------------------------------------------------------------------------
// bake-content — the PUBLISH step for the zero-database public site.
//
//   node scripts/bake-content.mjs [baseUrl]
//
// Pulls every published table from the CMS API (which reads the database)
// and writes it into src/content/*.ts as embedded TypeScript modules. After
// baking, the public site renders 100% from the bundle: no fetches, no API
// calls, no database — pages cannot blank or hang because there is nothing
// to load. The database is touched only when the admin publishes (this
// script) or a visitor submits a form (booking, contact, newsletter, order).
//
// Re-publish after admin edits:  bun run bake  →  commit  →  deploy.
// ---------------------------------------------------------------------------

import fs from "node:fs"
import path from "node:path"

const BASE = process.argv[2] || "http://localhost:3000"
const ROOT = path.resolve(import.meta.dirname, "..")
const OUT = path.join(ROOT, "src", "content")
fs.mkdirSync(OUT, { recursive: true })

async function pull(resource) {
  const res = await fetch(`${BASE}/api/cms/${resource}`)
  if (!res.ok) throw new Error(`GET ${resource} → ${res.status}`)
  return res.json()
}

const [settings, testimonials, services, serviceItems, packages, addons,
  gallery, products, productReviews, faqs, policies, cats, filterDefs,
  filterVals, mappings] = await Promise.all([
  pull("settings"), pull("testimonials"), pull("services"), pull("serviceItems"),
  pull("packages"), pull("addons"), pull("gallery"), pull("products"),
  pull("product_reviews"), pull("faqs"), pull("policies"),
  pull("pet_product_categories"), pull("pet_product_filters"),
  pull("pet_product_filter_values"), pull("pet_category_filters"),
])

// Category tree (with rolled-up visible product counts), same shape the
// storefront sidebar and breadcrumbs consume: { ready, categories, flat }.
const treeRes = await fetch(`${BASE}/api/shop/categories`)
const categoryTree = await treeRes.json()

// Wizard reference data (breeds, services, groomers, lookups) for the
// booking/consultation wizards.
const wizardRes = await fetch(`${BASE}/api/wizard/data`)
const wizardData = await wizardRes.json()

// ---- resolve filters per category (own mappings, else nearest ancestor) ----
const catById = new Map(cats.map((c) => [c.id, c]))
function filtersFor(categoryId) {
  const active = mappings
    .filter((m) => m.category_id === categoryId)
    .sort((a, b) => (a.display_order ?? 0) - (b.display_order ?? 0))
  const out = []
  for (const m of active) {
    const f = filterDefs.find((x) => x.id === m.filter_id)
    if (!f || f.is_active === false) continue
    out.push({
      id: f.id,
      name: f.name,
      slug: f.slug,
      filterType: f.filter_type,
      isGlobal: !!f.is_global,
      isMultiselect: !!f.is_multiselect,
      displayOrder: m.display_order ?? 0,
      values: filterVals
        .filter((v) => v.filter_id === f.id && v.is_active !== false)
        .sort((a, b) => (a.display_order ?? 0) - (b.display_order ?? 0))
        .map((v) => ({ id: v.id, name: v.name, slug: v.slug })),
    })
  }
  return out
}
const filtersByCategoryIndex = {}
const filterSets = []
const setIndexByJson = new Map()
for (const c of cats) {
  let list = filtersFor(c.id)
  if (!list.length) {
    let parentId = c.parent_id ?? null
    while (parentId != null) {
      const parent = catById.get(parentId)
      if (!parent) break
      const inherited = filtersFor(parent.id)
      if (inherited.length) { list = inherited; break }
      parentId = parent.parent_id ?? null
    }
  }
  if (!list.length) continue
  const key = JSON.stringify(list)
  if (!setIndexByJson.has(key)) {
    setIndexByJson.set(key, filterSets.length)
    filterSets.push(list)
  }
  filtersByCategoryIndex[c.id] = setIndexByJson.get(key)
}

// ---- sanity: wizard shape ----
for (const k of ["breeds", "services", "groomers", "lookups"]) {
  if (!(k in wizardData)) throw new Error(`wizard data missing "${k}"`)
}
if (!categoryTree || !Array.isArray(categoryTree.categories)) {
  throw new Error("category tree malformed")
}

const J = (v) => JSON.stringify(v, null, 2)

const banner = (name) => `// ---------------------------------------------------------------------------
// ${name} — AUTO-GENERATED by scripts/bake-content.mjs. DO NOT EDIT BY HAND.
//
// This is the site's PUBLISHED CONTENT, baked into the bundle at publish
// time. The public site renders from this file with ZERO database access:
// no fetches, no API calls, no loading states, nothing that can blank the
// page. To publish admin edits, run:  bun run bake  (then commit + deploy).
// ---------------------------------------------------------------------------
`

fs.writeFileSync(
  path.join(OUT, "site-content.ts"),
  `${banner("src/content/site-content.ts")}
export type CmsRow = Record<string, any>

export type CategoryNode = {
  id: number
  name: string
  slug: string
  parentId: number | null
  productCount: number
  children: CategoryNode[]
}

export type CategoryFilter = {
  id: number
  name: string
  slug: string
  filterType: "select" | "range" | "boolean"
  isGlobal: boolean
  isMultiselect: boolean
  displayOrder: number
  values: { id: number; name: string; slug: string }[]
}

export const settings: Record<string, string> = ${J(settings)}

export const testimonials: CmsRow[] = ${J(testimonials)}

export const services: CmsRow[] = ${J(services)}

export const serviceItems: CmsRow[] = ${J(serviceItems)}

export const packages: CmsRow[] = ${J(packages)}

export const addons: CmsRow[] = ${J(addons)}

export const gallery: CmsRow[] = ${J(gallery)}

export const products: CmsRow[] = ${J(products)}

export const productReviews: CmsRow[] = ${J(productReviews)}

export const faqs: CmsRow[] = ${J(faqs)}

export const policies: CmsRow[] = ${J(policies)}

export const categoryTree: { ready: boolean; categories: CategoryNode[]; flat: CategoryNode[] } = ${J(categoryTree)}

// Filter framework — deduped sets (categories share the department's set).
export const filterSets: CategoryFilter[][] = ${J(filterSets)}

export const filtersByCategoryIndex: Record<number, number> = ${J(filtersByCategoryIndex)}

export function filtersForCategory(categoryId: number): CategoryFilter[] {
  const idx = filtersByCategoryIndex[categoryId]
  return idx == null ? [] : filterSets[idx] || []
}

// ---- pure tree helpers (shared by the shop pages; no server-only import) ----

export function findNode(nodes: CategoryNode[], predicate: (n: CategoryNode) => boolean): CategoryNode | null {
  for (const n of nodes) {
    if (predicate(n)) return n
    const hit = findNode(n.children, predicate)
    if (hit) return hit
  }
  return null
}

export function collectSubtreeIds(node: CategoryNode): number[] {
  return [node.id, ...node.children.flatMap(collectSubtreeIds)]
}
`,
)

fs.writeFileSync(
  path.join(OUT, "wizard-data.ts"),
  `${banner("src/content/wizard-data.ts")}
export const wizardData: {
  breeds: any[]
  services: any[]
  groomers: any[]
  lookups: Record<string, any[]>
} = ${J(wizardData)}
`,
)

console.log("baked:")
for (const [name, rows] of Object.entries({
  settings: Object.keys(settings).length, testimonials, services, serviceItems,
  packages, addons, gallery, products, productReviews, faqs, policies,
  categories: categoryTree.categories,
})) {
  console.log(`  ${name.padEnd(16)} ${rows.length}`)
}
console.log(`  wizard breeds     ${wizardData.breeds.length}`)
console.log(`  wizard lookups    ${Object.keys(wizardData.lookups).length} groups`)
console.log(`  filter sets       ${filterSets.length} unique (${Object.keys(filtersByCategoryIndex).length} categories mapped)`)
