-- ============================================================================
-- Multi-Tenant Role Isolation Migration
-- Creates the profiles, user_roles, and trigger system for 5 role paths.
-- Run this in the Supabase SQL Editor.
-- ============================================================================

-- Create custom enum for the 5 strict system roles
CREATE TYPE user_app_role AS ENUM ('learner', 'shop_customer', 'grooming_customer', 'groomer', 'admin');

-- Create core profiles table linked directly to Supabase Auth
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create roles join table (supports user being one-of-many or one-of-one)
CREATE TABLE public.user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    role user_app_role NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(user_id, role)
);

-- Enable Row Level Security
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Secure Profiles policies
CREATE POLICY "Allow public read access to profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Allow users to update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Secure Roles policies (Only Admins can modify roles; users can view their own roles)
CREATE POLICY "Allow users to read their own roles" ON public.user_roles FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Allow admins full control of user roles" ON public.user_roles FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.user_roles 
        WHERE user_roles.user_id = auth.uid() AND user_roles.role = 'admin'::user_app_role
    )
);

-- Automatic Profile and Role Seeding on User Signup (Email & Google OAuth)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    -- 1. Insert the newly authenticated account into the public profiles table
    INSERT INTO public.profiles (id, email, full_name)
    VALUES (
        NEW.id, 
        NEW.email, 
        COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', 'New Member')
    );

    -- 2. Seed a default role (all new users get 'learner' status)
    INSERT INTO public.user_roles (user_id, role)
    VALUES (NEW.id, 'learner'::user_app_role);

    -- 3. Specific assignment: test account becomes admin immediately
    IF NEW.email = 'etnologicinc@gmail.com' THEN
        INSERT INTO public.user_roles (user_id, role)
        VALUES (NEW.id, 'admin'::user_app_role);
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger the setup whenever an auth account finishes creation
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================================
-- Notification: Send email to management when a new user enrolls
-- Uses Supabase's pg_net extension to POST to the Resend email API.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.notify_management_new_enrollment()
RETURNS TRIGGER AS $$
DECLARE
    user_email TEXT;
    user_name TEXT;
BEGIN
    SELECT email, full_name INTO user_email, user_name
    FROM public.profiles WHERE id = NEW.user_id;
    
    -- Fire HTTP request to a Next.js webhook which sends the email via Resend
    -- This avoids needing pg_net enabled — the Next.js route handles the email
    PERFORM net.http_post(
        url := COALESCE(
            current_setting('app.management_webhook_url', true),
            'https://aapawz.com/api/notify/enrollment'
        ),
        headers := '{"Content-Type": "application/json"}'::jsonb,
        body := json_build_object(
            'email', user_email,
            'name', user_name,
            'user_id', NEW.user_id,
            'role', NEW.role::text,
            'timestamp', NOW()
        )::jsonb
    ) WHERE EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_net');
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger enrollment notification when a new learner role is assigned
CREATE OR REPLACE TRIGGER on_new_learner_enrollment
    AFTER INSERT ON public.user_roles
    FOR EACH ROW WHEN (NEW.role = 'learner'::user_app_role)
    EXECUTE FUNCTION public.notify_management_new_enrollment();
