-- ============================================================================
-- All About Pawz — Multi-Tenant Role Isolation Migration
-- Run this in your Supabase SQL Editor.
-- Creates: profiles, user_roles, RLS policies, auto-seed trigger, email trigger
-- ============================================================================

-- Create custom enum for the 5 strict system roles
CREATE TYPE user_app_role AS ENUM ('learner', 'shop_customer', 'grooming_customer', 'groomer', 'admin');

-- Create core profiles table linked directly to Supabase Auth
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create roles join table (Supports user being one-of-many or one-of-one)
CREATE TABLE IF NOT EXISTS public.user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    role user_app_role NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(user_id, role)
);

-- Enable Row Level Security
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Secure Profiles policies
CREATE POLICY "Allow public read access to profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Allow users to update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Secure Roles policies
CREATE POLICY "Allow users to read their own roles" ON public.user_roles FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Allow admins full control of user roles" ON public.user_roles FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.user_roles 
        WHERE user_roles.user_id = auth.uid() AND user_roles.role = 'admin'::user_app_role
    )
);

-- ============================================================================
-- Automatic Profile and Role Seeding on User Signup (Email & Google OAuth)
-- ============================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, full_name)
    VALUES (
        NEW.id, 
        NEW.email, 
        COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', 'New Member')
    );

    INSERT INTO public.user_roles (user_id, role)
    VALUES (NEW.id, 'learner'::user_app_role);

    -- SPECIFIC ASSIGNMENT: Turn the test account into a platform Admin
    IF NEW.email = 'etnologicinc@gmail.com' THEN
        INSERT INTO public.user_roles (user_id, role)
        VALUES (NEW.id, 'admin'::user_app_role);
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================================
-- Notification: Email management when a new learner enrolls
-- This trigger fires when a new profile is created and calls the
-- notify_management_of_enrollment function which uses the Supabase
-- Edge Function (pg_net) to send an HTTP request to the app's
-- /api/notify/enrollment endpoint, which sends the email via Resend.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.notify_management_of_enrollment()
RETURNS TRIGGER AS $$
BEGIN
    -- Use pg_net to call the app's notification endpoint
    -- The endpoint sends an email to management via Resend
    PERFORM net.http_post(
        url := COALESCE(
            current_setting('app.site_url', true),
            'https://aapawz.com'
        ) || '/api/notify/enrollment',
        headers := '{"Content-Type": "application/json"}'::jsonb,
        body := json_build_object(
            'email', NEW.email,
            'name', COALESCE(NEW.full_name, 'New Member'),
            'user_id', NEW.id,
            'timestamp', NOW()
        )::jsonb
    );
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_new_enrollment
    AFTER INSERT ON public.profiles
    FOR EACH ROW EXECUTE FUNCTION public.notify_management_of_enrollment();
